### ISSUE TITLE
App crash on speech listening

### ISSUE THREAD

**Issue by Sprechen** [wit-ai/wit-android-eval#3]
On Nexus 5 with Marshmallow, the app crashes when starting listening to speech:

01-25 16:20:48.544 17389-17389/? I/art: Late-enabling -Xcheck:jni
01-25 16:20:48.574 17389-17397/? I/art: Debugger is no longer active
01-25 16:20:48.674 17389-17421/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-25 16:20:48.705 17389-17421/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
01-25 16:20:48.707 17389-17421/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-25 16:20:50.139 17389-17389/ai.wit.eval.wit_eval D/ai.wit.sdk.Wit: streamRawAudio started.
01-25 16:20:50.141 17389-17461/ai.wit.eval.wit_eval D/Wit: Requesting SPEECH ....audio/raw;encoding=signed-integer;bits=16;rate=16000;endian=little
01-25 16:20:50.157 17389-17461/ai.wit.eval.wit_eval D/Wit: Posting speech to https://api.wit.ai/speech?v=20141022&context=%7B%22reference_time%22%3A%222016-01-25T16%3A20Z%22%2C%22location%22%3A%7B%22latitude%22%3A44.414414414414416%2C%22longitude%22%3A8.904368347827425%7D%7D
01-25 16:20:51.008 17389-17460/ai.wit.eval.wit_eval E/AndroidRuntime: FATAL EXCEPTION: Thread-130415
                                                                      Process: ai.wit.eval.wit_eval, PID: 17389
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=12800; index=12800
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.short2byte(WitMic.java:227)
                                                                          at ai.wit.sdk.WitMic$SamplesReaderThread.run(WitMic.java:207)
01-25 16:24:51.887 17389-17397/ai.wit.eval.wit_eval W/art: Suspending all threads took: 11.165ms

**Comment by imomin** [comment]
same here.

**Comment by patrickhuie19** [comment]
same - any ideas to fix it?

**Comment by RicardoTrindade** [comment]
It seems that this is happening on Android 6.0 as older versions can run it with no problems

**Comment by Kameswari** [comment]
I am also facing the same issue. Any one found solution for this?
